[supabase]
url = "https://ktamncrqewwghkdqimho.supabase.co"
anon_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0YW1uY3JxZXd3Z2hrZHFpbWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MDIxNjYsImV4cCI6MjEwMDk3ODE2Nn0.Umqadj0FiccaecrRPcFCM4-O0FmGAY2xWDjW8UDJirM"