[supabase]
url = "https://zybthhisqpspulmerupt.supabase.co"
anon_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5YnRoaGlzcXBzcHVsbWVydXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE0MzA5OTAsImV4cCI6MjA5NzAwNjk5MH0.luXdFzkHKSpoqxf3ypFKPGpi2DQ_Lj60DH3K2pB_bMA"